[package]
authors = ["omnect@conplement.de"]
edition = "2021"
homepage = "https://www.omnect.io/home"
license = "MIT OR Apache-2.0"
name = "modemmanager"
readme = "README.md"
repository = "git@github.com:omnect/modemmanager.git"
version = "0.3.4"

[dependencies]
num = { version = "0.4", default-features = false }
num-derive = { version = "0.4", default-features = false }
num-traits = { version = "0.2", default-features = false }
zbus = { version = "5.3", default-features = false, features = ["tokio"] }
modemmanager-sys = { git = "https://github.com/omnect/modemmanager-sys.git", features = [
  "zbus",
], tag = "0.1.4" }

[features]
ModemManager-1_20 = []
default = ["ModemManager-1_20"]
